#!/usr/bin/env python

import xmlrpclib
import ssl
import util
import sys
import os

def printf(format,*args): sys.stdout.write(format%args)

def usage(prog):
    printf("Usage is %s <host> <ip> [ttl]\n",prog)
    printf("\n")
    printf("set the host name to the ip address\n")

if __name__=="__main__":
    context=ssl._create_unverified_context()
    (url,domain,baseDomain,cred) = util.getCurrentDomain()
    prog = os.path.basename(sys.argv[0])
    if len(sys.argv)<3:
        usage(prog)
        sys.exit()
    host = sys.argv[1]
    ip = sys.argv[2]
    s = xmlrpclib.ServerProxy(url,allow_none=True, context=context)
    
    if len(sys.argv)>=4:
        ttl = int(sys.argv[3])
    else:
        ttl = None
    res = s.addARecord(cred,host,ip,ttl)
    args = (res["updated"],res["added"],res["total"])
    printf("updated=%i added=%i totalIps = %i\n",*args)
