#!/usr/bin/env python

import xmlrpclib
import ssl
import util
import sys
import os

context = ssl._create_unverified_context()

def printf(format,*args): sys.stdout.write(format%args)

def usage(prog):
    printf("Usage is %s <host> <ip1..ipN>\n",prog)
    printf("\n")
    printf("delete the A record for the host with the ip\n")
    printf("If you want to delete all the ip records run\n")
    printf("delHost\n")

if __name__=="__main__":
    (url,domain,baseDomain,cred) = util.getCurrentDomain()
    prog = os.path.basename(sys.argv[0])
    if len(sys.argv)<2:
        usage(prog)
        sys.exit()
    host = sys.argv[1]
    s = xmlrpclib.ServerProxy(url,context=context)
    ips = sys.argv[2:]
    deletedIps = s.delARecord(cred,host,*ips)
    for ip in deletedIps:
        printf("deleted %s\n",ip)
