#!/usr/bin/env python

import xmlrpclib
import util
import ssl
import sys
import os

context=ssl._create_unverified_context()

def printf(format,*args): sys.stdout.write(format%args)

def usage(prog):
    printf("Usage is %s <name>\n",prog)
    printf("\n")
    printf("delete the A record for the host with the ip\n")
    printf("If you want to delete all the ip records run\n")
    printf("delHost\n")

if __name__=="__main__":
    (url,domain,baseDomain,cred) = util.getCurrentDomain()
    prog = os.path.basename(sys.argv[0])
    if len(sys.argv)<2:
        usage(prog)
        sys.exit()
    name = sys.argv[1]
    s = xmlrpclib.ServerProxy(url, context=context)
    deletedNames = s.delCNAMERecord(cred,name)
    for dname in deletedNames:
        printf("deleted %s\n",dname)
