#!/usr/bin/env python

import xmlrpclib
import util
import sys

def printf(format,*args): sys.stdout.write(format%args)

if __name__=="__main__":
    conf = util.load_json(util.CONF_FILE)
    cd = conf["curr_domain"] if conf.has_key("curr_domain") else "None"
    printf("Current domain is set to: %s\n",cd)
    printf("\n")
    printf("Domains configured in %s as follows:\n",util.CONF_FILE)
    for k in sorted(conf["domains"].keys()):
        domain = util.pad(20," ",k,side="RIGHT")
        url = conf["domains"][k]["url"]
        printf("  %s %s\n",domain,url)
