#!/usr/bin/env python

import xmlrpclib
import util
import sys

def printf(format,*args): sys.stdout.write(format%args)

if __name__=="__main__":
    (url,curr_domain,baseDomain,cred) = util.getCurrentDomain()
    s = xmlrpclib.ServerProxy(url)
    serial = s.getSerial(cred)
    printf("\n")
    printf("Serial for domain %s:  %i\n",curr_domain,serial)
