#!/usr/bin/env python

import xmlrpclib
import util
import sys
import ssl
import os

context = ssl._create_unverified_context()

def printf(format,*args): sys.stdout.write(format%args)

if __name__=="__main__":
    (url,domain,baseDomain,cred) = util.getCurrentDomain()
    s = xmlrpclib.ServerProxy(url,allow_none=True,context=context)
    printf("%s\n", s.reload(cred))
